---
- include_tasks:        '../tasks/remove_files.yml'
- include_tasks:        '../tasks/install_files.yml'
- include_tasks:        '../tasks/template_files.yml'
- assert:
    that:               True
    quiet:              True
  changed_when:         True
  when:                 remove_files_result.changed
                        or template_files_result.changed
                        or install_files_result.changed
  notify:               'run updates'
